#!/bin/bash

# --- CONFIGURAÇÕES ---
NOME_APP="meuelevador"          
CONTAINER_DB="srv-captain--$NOME_APP-db"
CONTAINER_SITE="srv-captain--$NOME_APP-com"
USER_DB="root"              
SENHA_DB="!rD3EvunQx5dRBgEa"         
NOME_DB="meuelevador"               

srv-captain--meuelevador-com 
 

DIRETORIO_BACKUP="/home/ubuntu/scripts"
 
NOME_ARQUIVO="dump_$(date +%d-%m-%Y_%H_%M_%S).sql"
NOME_COMPACTADO="database_$(date +%d-%m-%Y_%H_%M_%S)"
REMOTE_RCLONE="gdrive:Backups"    

# Criar pasta temporária se não existir
# mkdir -p $DIRETORIO_BACKUP

echo "--- Iniciando backup de $NOME_APP ---"
docker exec -it $(docker ps --filter name=$CONTAINER_DB -q) sh -c 'mariadb-dump -u '$USER_DB' -p'$SENHA_DB' --all-databases' > $NOME_ARQUIVO
 
echo "--- Compactando arquivo de banco de dados $NOME_APP ---"

tar -czf $DIRETORIO_BACKUP/$NOME_COMPACTADO.tar.gz $DIRETORIO_BACKUP/$NOME_ARQUIVO

echo "--- Fazendo backup do wordpress $NOME_APP ---"

 
docker exec -i $(docker ps -qf name=$CONTAINER_SITE) \
tar -czf - -C /var/www/vhosts/localhost html \
> wordpress.tar.gz
 
# 3. Upload para Google Drive via Rclone
# echo "Enviando para o Google Drive..."
# rclone move $DIRETORIO_BACKUP/$NOME_ARQUIVO $REMOTE_RCLONE

# # 4. Limpeza
rm $DIRETORIO_BACKUP/$NOME_ARQUIVO

echo "Log de backup executada em: $(date)" >> /home/marviorocha/log_backup.txt
echo "--- Backup concluído com sucesso em $(date) ---"

 
